version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: dgi-postgres
    environment:
      POSTGRES_DB: dgiapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dgi-network
    restart: unless-stopped

  # Spring Boot backend
  backend:
    build: ./backend
    container_name: dgi-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dgiapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - dgi-network
    restart: unless-stopped

  # React frontend
  frontend:
    build: ./frontend
    container_name: dgi-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dgi-network
    restart: unless-stopped

networks:
  dgi-network:
    driver: bridge

volumes:
  postgres-data:
